package mx.utxj.ti.estadia.model.pojos;
// Generated 23/06/2019 08:08:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carreras generated by hbm2java
 */
public class Carreras  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String nivel;
     private String director;
     private String area;
     private Set asignacions = new HashSet(0);
     private Set periodos = new HashSet(0);
     private Set alumnoses = new HashSet(0);
     private Set personases = new HashSet(0);

    public Carreras() {
    }

	
    public Carreras(String nombre, String nivel, String director, String area) {
        this.nombre = nombre;
        this.nivel = nivel;
        this.director = director;
        this.area = area;
    }
    public Carreras(String nombre, String nivel, String director, String area, Set asignacions, Set periodos, Set alumnoses, Set personases) {
       this.nombre = nombre;
       this.nivel = nivel;
       this.director = director;
       this.area = area;
       this.asignacions = asignacions;
       this.periodos = periodos;
       this.alumnoses = alumnoses;
       this.personases = personases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public Set getAsignacions() {
        return this.asignacions;
    }
    
    public void setAsignacions(Set asignacions) {
        this.asignacions = asignacions;
    }
    public Set getPeriodos() {
        return this.periodos;
    }
    
    public void setPeriodos(Set periodos) {
        this.periodos = periodos;
    }
    public Set getAlumnoses() {
        return this.alumnoses;
    }
    
    public void setAlumnoses(Set alumnoses) {
        this.alumnoses = alumnoses;
    }
    public Set getPersonases() {
        return this.personases;
    }
    
    public void setPersonases(Set personases) {
        this.personases = personases;
    }




}


