package mx.utxj.ti.estadia.model.pojos;
// Generated 23/06/2019 08:08:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ContactoEmpresa generated by hbm2java
 */
public class ContactoEmpresa  implements java.io.Serializable {


     private Integer id;
     private Empresas empresas;
     private String correo;
     private String direccion;
     private String ubicacion;
     private String encargado;
     private Set personases = new HashSet(0);

    public ContactoEmpresa() {
    }

	
    public ContactoEmpresa(Empresas empresas, String correo, String direccion, String ubicacion, String encargado) {
        this.empresas = empresas;
        this.correo = correo;
        this.direccion = direccion;
        this.ubicacion = ubicacion;
        this.encargado = encargado;
    }
    public ContactoEmpresa(Empresas empresas, String correo, String direccion, String ubicacion, String encargado, Set personases) {
       this.empresas = empresas;
       this.correo = correo;
       this.direccion = direccion;
       this.ubicacion = ubicacion;
       this.encargado = encargado;
       this.personases = personases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }
    public String getEncargado() {
        return this.encargado;
    }
    
    public void setEncargado(String encargado) {
        this.encargado = encargado;
    }
    public Set getPersonases() {
        return this.personases;
    }
    
    public void setPersonases(Set personases) {
        this.personases = personases;
    }




}


