package mx.utxj.ti.estadia.model.pojos;
// Generated 23/06/2019 08:08:20 PM by Hibernate Tools 4.3.1



/**
 * DetallePostulaciones generated by hbm2java
 */
public class DetallePostulaciones  implements java.io.Serializable {


     private Integer id;
     private Postulaciones postulacionesById;
     private Postulaciones postulacionesByPostulacionesId;
     private String descripcion;

    public DetallePostulaciones() {
    }

    public DetallePostulaciones(Postulaciones postulacionesById, Postulaciones postulacionesByPostulacionesId, String descripcion) {
       this.postulacionesById = postulacionesById;
       this.postulacionesByPostulacionesId = postulacionesByPostulacionesId;
       this.descripcion = descripcion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Postulaciones getPostulacionesById() {
        return this.postulacionesById;
    }
    
    public void setPostulacionesById(Postulaciones postulacionesById) {
        this.postulacionesById = postulacionesById;
    }
    public Postulaciones getPostulacionesByPostulacionesId() {
        return this.postulacionesByPostulacionesId;
    }
    
    public void setPostulacionesByPostulacionesId(Postulaciones postulacionesByPostulacionesId) {
        this.postulacionesByPostulacionesId = postulacionesByPostulacionesId;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


