package mx.utxj.ti.estadia.model.pojos;
// Generated 23/06/2019 08:08:20 PM by Hibernate Tools 4.3.1



/**
 * DetallePropuesta generated by hbm2java
 */
public class DetallePropuesta  implements java.io.Serializable {


     private int id;
     private Propuesta propuesta;
     private String numVacantes;
     private String actividadesRealizar;

    public DetallePropuesta() {
    }

	
    public DetallePropuesta(int id, Propuesta propuesta) {
        this.id = id;
        this.propuesta = propuesta;
    }
    public DetallePropuesta(int id, Propuesta propuesta, String numVacantes, String actividadesRealizar) {
       this.id = id;
       this.propuesta = propuesta;
       this.numVacantes = numVacantes;
       this.actividadesRealizar = actividadesRealizar;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Propuesta getPropuesta() {
        return this.propuesta;
    }
    
    public void setPropuesta(Propuesta propuesta) {
        this.propuesta = propuesta;
    }
    public String getNumVacantes() {
        return this.numVacantes;
    }
    
    public void setNumVacantes(String numVacantes) {
        this.numVacantes = numVacantes;
    }
    public String getActividadesRealizar() {
        return this.actividadesRealizar;
    }
    
    public void setActividadesRealizar(String actividadesRealizar) {
        this.actividadesRealizar = actividadesRealizar;
    }




}


