package mx.utxj.ti.estadia.model.pojos;
// Generated 23/06/2019 08:08:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresas generated by hbm2java
 */
public class Empresas  implements java.io.Serializable {


     private Integer id;
     private Ubicaciones ubicaciones;
     private String nombre;
     private String tipo;
     private String caracteristicas;
     private String informacion;
     private String giro;
     private String rol;
     private String vinculada;
     private String rfc;
     private String tamaño;
     private Set evaluacionEstadias = new HashSet(0);
     private Set propuestas = new HashSet(0);
     private Set contactoEmpresas = new HashSet(0);

    public Empresas() {
    }

	
    public Empresas(Ubicaciones ubicaciones, String nombre, String tipo, String caracteristicas, String informacion, String giro, String rol, String vinculada, String rfc, String tamaño) {
        this.ubicaciones = ubicaciones;
        this.nombre = nombre;
        this.tipo = tipo;
        this.caracteristicas = caracteristicas;
        this.informacion = informacion;
        this.giro = giro;
        this.rol = rol;
        this.vinculada = vinculada;
        this.rfc = rfc;
        this.tamaño = tamaño;
    }
    public Empresas(Ubicaciones ubicaciones, String nombre, String tipo, String caracteristicas, String informacion, String giro, String rol, String vinculada, String rfc, String tamaño, Set evaluacionEstadias, Set propuestas, Set contactoEmpresas) {
       this.ubicaciones = ubicaciones;
       this.nombre = nombre;
       this.tipo = tipo;
       this.caracteristicas = caracteristicas;
       this.informacion = informacion;
       this.giro = giro;
       this.rol = rol;
       this.vinculada = vinculada;
       this.rfc = rfc;
       this.tamaño = tamaño;
       this.evaluacionEstadias = evaluacionEstadias;
       this.propuestas = propuestas;
       this.contactoEmpresas = contactoEmpresas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ubicaciones getUbicaciones() {
        return this.ubicaciones;
    }
    
    public void setUbicaciones(Ubicaciones ubicaciones) {
        this.ubicaciones = ubicaciones;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getCaracteristicas() {
        return this.caracteristicas;
    }
    
    public void setCaracteristicas(String caracteristicas) {
        this.caracteristicas = caracteristicas;
    }
    public String getInformacion() {
        return this.informacion;
    }
    
    public void setInformacion(String informacion) {
        this.informacion = informacion;
    }
    public String getGiro() {
        return this.giro;
    }
    
    public void setGiro(String giro) {
        this.giro = giro;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getVinculada() {
        return this.vinculada;
    }
    
    public void setVinculada(String vinculada) {
        this.vinculada = vinculada;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getTamaño() {
        return this.tamaño;
    }
    
    public void setTamaño(String tamaño) {
        this.tamaño = tamaño;
    }
    public Set getEvaluacionEstadias() {
        return this.evaluacionEstadias;
    }
    
    public void setEvaluacionEstadias(Set evaluacionEstadias) {
        this.evaluacionEstadias = evaluacionEstadias;
    }
    public Set getPropuestas() {
        return this.propuestas;
    }
    
    public void setPropuestas(Set propuestas) {
        this.propuestas = propuestas;
    }
    public Set getContactoEmpresas() {
        return this.contactoEmpresas;
    }
    
    public void setContactoEmpresas(Set contactoEmpresas) {
        this.contactoEmpresas = contactoEmpresas;
    }




}


