package mx.utxj.ti.estadia.model.pojos;
// Generated 23/06/2019 08:08:20 PM by Hibernate Tools 4.3.1



/**
 * EvaluacionEstadia generated by hbm2java
 */
public class EvaluacionEstadia  implements java.io.Serializable {


     private EvaluacionEstadiaId id;
     private Empresas empresas;
     private String calificacion;
     private String comentarios;

    public EvaluacionEstadia() {
    }

    public EvaluacionEstadia(EvaluacionEstadiaId id, Empresas empresas, String calificacion, String comentarios) {
       this.id = id;
       this.empresas = empresas;
       this.calificacion = calificacion;
       this.comentarios = comentarios;
    }
   
    public EvaluacionEstadiaId getId() {
        return this.id;
    }
    
    public void setId(EvaluacionEstadiaId id) {
        this.id = id;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public String getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(String calificacion) {
        this.calificacion = calificacion;
    }
    public String getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(String comentarios) {
        this.comentarios = comentarios;
    }




}


