package mx.utxj.ti.estadia.model.pojos;
// Generated 23/06/2019 08:08:20 PM by Hibernate Tools 4.3.1



/**
 * EvaluacionEstadiaId generated by hbm2java
 */
public class EvaluacionEstadiaId  implements java.io.Serializable {


     private int id;
     private int empresasId;

    public EvaluacionEstadiaId() {
    }

    public EvaluacionEstadiaId(int id, int empresasId) {
       this.id = id;
       this.empresasId = empresasId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getEmpresasId() {
        return this.empresasId;
    }
    
    public void setEmpresasId(int empresasId) {
        this.empresasId = empresasId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EvaluacionEstadiaId) ) return false;
		 EvaluacionEstadiaId castOther = ( EvaluacionEstadiaId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getEmpresasId()==castOther.getEmpresasId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getEmpresasId();
         return result;
   }   


}


