package mx.utxj.ti.estadia.model.pojos;
// Generated 23/06/2019 08:08:20 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Periodo generated by hbm2java
 */
public class Periodo  implements java.io.Serializable {


     private Integer id;
     private Carreras carreras;
     private String tipo;
     private Date fecha;

    public Periodo() {
    }

    public Periodo(Carreras carreras, String tipo, Date fecha) {
       this.carreras = carreras;
       this.tipo = tipo;
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Carreras getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Carreras carreras) {
        this.carreras = carreras;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


