package mx.utxj.ti.estadia.model.pojos;
// Generated 23/06/2019 08:08:20 PM by Hibernate Tools 4.3.1



/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private Integer id;
     private Alumnos alumnos;
     private Carreras carreras;
     private ContactoEmpresa contactoEmpresa;
     private Personal personal;
     private Usuario usuario;
     private String nombre;
     private String apellidos;
     private String tipo;

    public Personas() {
    }

    public Personas(Alumnos alumnos, Carreras carreras, ContactoEmpresa contactoEmpresa, Personal personal, Usuario usuario, String nombre, String apellidos, String tipo) {
       this.alumnos = alumnos;
       this.carreras = carreras;
       this.contactoEmpresa = contactoEmpresa;
       this.personal = personal;
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.tipo = tipo;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public Carreras getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Carreras carreras) {
        this.carreras = carreras;
    }
    public ContactoEmpresa getContactoEmpresa() {
        return this.contactoEmpresa;
    }
    
    public void setContactoEmpresa(ContactoEmpresa contactoEmpresa) {
        this.contactoEmpresa = contactoEmpresa;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


