package mx.utxj.ti.estadia.model.pojos;
// Generated 23/06/2019 08:08:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private Integer id;
     private String cargo;
     private String nombre;
     private String apellido;
     private String correo;
     private Set propuestas = new HashSet(0);
     private Set personases = new HashSet(0);

    public Personal() {
    }

	
    public Personal(String cargo, String nombre, String apellido, String correo) {
        this.cargo = cargo;
        this.nombre = nombre;
        this.apellido = apellido;
        this.correo = correo;
    }
    public Personal(String cargo, String nombre, String apellido, String correo, Set propuestas, Set personases) {
       this.cargo = cargo;
       this.nombre = nombre;
       this.apellido = apellido;
       this.correo = correo;
       this.propuestas = propuestas;
       this.personases = personases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set getPropuestas() {
        return this.propuestas;
    }
    
    public void setPropuestas(Set propuestas) {
        this.propuestas = propuestas;
    }
    public Set getPersonases() {
        return this.personases;
    }
    
    public void setPersonases(Set personases) {
        this.personases = personases;
    }




}


