package mx.utxj.ti.estadia.model.pojos;
// Generated 23/06/2019 08:08:20 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Postulaciones generated by hbm2java
 */
public class Postulaciones  implements java.io.Serializable {


     private Integer id;
     private Propuesta propuesta;
     private Date fechaPostulacion;
     private String observaciones;
     private String estatus;
     private DetallePostulaciones detallePostulacionesById;
     private Set detallePostulacionesesForPostulacionesId = new HashSet(0);

    public Postulaciones() {
    }

	
    public Postulaciones(Propuesta propuesta, Date fechaPostulacion, String observaciones, String estatus) {
        this.propuesta = propuesta;
        this.fechaPostulacion = fechaPostulacion;
        this.observaciones = observaciones;
        this.estatus = estatus;
    }
    public Postulaciones(Propuesta propuesta, Date fechaPostulacion, String observaciones, String estatus, DetallePostulaciones detallePostulacionesById, Set detallePostulacionesesForPostulacionesId) {
       this.propuesta = propuesta;
       this.fechaPostulacion = fechaPostulacion;
       this.observaciones = observaciones;
       this.estatus = estatus;
       this.detallePostulacionesById = detallePostulacionesById;
       this.detallePostulacionesesForPostulacionesId = detallePostulacionesesForPostulacionesId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Propuesta getPropuesta() {
        return this.propuesta;
    }
    
    public void setPropuesta(Propuesta propuesta) {
        this.propuesta = propuesta;
    }
    public Date getFechaPostulacion() {
        return this.fechaPostulacion;
    }
    
    public void setFechaPostulacion(Date fechaPostulacion) {
        this.fechaPostulacion = fechaPostulacion;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public DetallePostulaciones getDetallePostulacionesById() {
        return this.detallePostulacionesById;
    }
    
    public void setDetallePostulacionesById(DetallePostulaciones detallePostulacionesById) {
        this.detallePostulacionesById = detallePostulacionesById;
    }
    public Set getDetallePostulacionesesForPostulacionesId() {
        return this.detallePostulacionesesForPostulacionesId;
    }
    
    public void setDetallePostulacionesesForPostulacionesId(Set detallePostulacionesesForPostulacionesId) {
        this.detallePostulacionesesForPostulacionesId = detallePostulacionesesForPostulacionesId;
    }




}


