package mx.utxj.ti.estadia.model.pojos;
// Generated 23/06/2019 08:08:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Propuesta generated by hbm2java
 */
public class Propuesta  implements java.io.Serializable {


     private int id;
     private Alumnos alumnos;
     private Empresas empresas;
     private Personal personal;
     private String descripcionPropuesta;
     private String vigencia;
     private String requisitos;
     private String totalVacantes;
     private String tipo;
     private Set asignacions = new HashSet(0);
     private Set postulacioneses = new HashSet(0);
     private Set detallePropuestas = new HashSet(0);

    public Propuesta() {
    }

	
    public Propuesta(int id, Alumnos alumnos, Empresas empresas, Personal personal, String descripcionPropuesta, String vigencia, String requisitos, String totalVacantes, String tipo) {
        this.id = id;
        this.alumnos = alumnos;
        this.empresas = empresas;
        this.personal = personal;
        this.descripcionPropuesta = descripcionPropuesta;
        this.vigencia = vigencia;
        this.requisitos = requisitos;
        this.totalVacantes = totalVacantes;
        this.tipo = tipo;
    }
    public Propuesta(int id, Alumnos alumnos, Empresas empresas, Personal personal, String descripcionPropuesta, String vigencia, String requisitos, String totalVacantes, String tipo, Set asignacions, Set postulacioneses, Set detallePropuestas) {
       this.id = id;
       this.alumnos = alumnos;
       this.empresas = empresas;
       this.personal = personal;
       this.descripcionPropuesta = descripcionPropuesta;
       this.vigencia = vigencia;
       this.requisitos = requisitos;
       this.totalVacantes = totalVacantes;
       this.tipo = tipo;
       this.asignacions = asignacions;
       this.postulacioneses = postulacioneses;
       this.detallePropuestas = detallePropuestas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Alumnos getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Alumnos alumnos) {
        this.alumnos = alumnos;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public Personal getPersonal() {
        return this.personal;
    }
    
    public void setPersonal(Personal personal) {
        this.personal = personal;
    }
    public String getDescripcionPropuesta() {
        return this.descripcionPropuesta;
    }
    
    public void setDescripcionPropuesta(String descripcionPropuesta) {
        this.descripcionPropuesta = descripcionPropuesta;
    }
    public String getVigencia() {
        return this.vigencia;
    }
    
    public void setVigencia(String vigencia) {
        this.vigencia = vigencia;
    }
    public String getRequisitos() {
        return this.requisitos;
    }
    
    public void setRequisitos(String requisitos) {
        this.requisitos = requisitos;
    }
    public String getTotalVacantes() {
        return this.totalVacantes;
    }
    
    public void setTotalVacantes(String totalVacantes) {
        this.totalVacantes = totalVacantes;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getAsignacions() {
        return this.asignacions;
    }
    
    public void setAsignacions(Set asignacions) {
        this.asignacions = asignacions;
    }
    public Set getPostulacioneses() {
        return this.postulacioneses;
    }
    
    public void setPostulacioneses(Set postulacioneses) {
        this.postulacioneses = postulacioneses;
    }
    public Set getDetallePropuestas() {
        return this.detallePropuestas;
    }
    
    public void setDetallePropuestas(Set detallePropuestas) {
        this.detallePropuestas = detallePropuestas;
    }




}


