package mx.utxj.ti.estadia.model.pojos;
// Generated 23/06/2019 08:08:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ubicaciones generated by hbm2java
 */
public class Ubicaciones  implements java.io.Serializable {


     private Integer id;
     private String ciudad;
     private String distritoEstado;
     private String pais;
     private String region;
     private Set empresases = new HashSet(0);

    public Ubicaciones() {
    }

	
    public Ubicaciones(String ciudad, String distritoEstado, String pais, String region) {
        this.ciudad = ciudad;
        this.distritoEstado = distritoEstado;
        this.pais = pais;
        this.region = region;
    }
    public Ubicaciones(String ciudad, String distritoEstado, String pais, String region, Set empresases) {
       this.ciudad = ciudad;
       this.distritoEstado = distritoEstado;
       this.pais = pais;
       this.region = region;
       this.empresases = empresases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getDistritoEstado() {
        return this.distritoEstado;
    }
    
    public void setDistritoEstado(String distritoEstado) {
        this.distritoEstado = distritoEstado;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public Set getEmpresases() {
        return this.empresases;
    }
    
    public void setEmpresases(Set empresases) {
        this.empresases = empresases;
    }




}


